import os

# ===== CONFIG =====
FS = 16000
SECONDS = 6
DEVICE_ID = None
AUDIO_PROFILE = "home"  # "home" | "lab"

# Perfil HOME: comportamento mais proximo do original (sem filtros extra)
if AUDIO_PROFILE == "home":
    AUDIO_VAD_CALIBRATION_SECONDS = 0.18
    AUDIO_VAD_WAIT_FOR_SPEECH_SECONDS = 0.70
    AUDIO_VAD_MIN_RECORD_SECONDS = 0.55
    AUDIO_VAD_MAX_RECORD_SECONDS = 3.20
    AUDIO_VAD_SILENCE_HOLD_SECONDS = 0.35
    AUDIO_VAD_TRIGGER_FACTOR = 1.65
    AUDIO_VAD_MIN_RMS = 0.002
    AUDIO_MAX_GAIN = 4.50
    AUDIO_FILTER_ENABLED = False
    AUDIO_HIGHPASS_HZ = 90.0
    AUDIO_NOISE_GATE_FACTOR = 1.9
    AUDIO_NOISE_GATE_BLEND = 0.18
    AUDIO_NOISE_PROFILE_SUBTRACT_ENABLED = False
    AUDIO_NOISE_SUBTRACT_FACTOR = 1.0
    AUDIO_NOISE_FLOOR_KEEP = 0.0
else:
    # Perfil LAB: robusto para ruido de fundo constante
    AUDIO_VAD_CALIBRATION_SECONDS = 0.28
    AUDIO_VAD_WAIT_FOR_SPEECH_SECONDS = 0.90
    AUDIO_VAD_MIN_RECORD_SECONDS = 0.65
    AUDIO_VAD_MAX_RECORD_SECONDS = 3.60
    AUDIO_VAD_SILENCE_HOLD_SECONDS = 0.42
    AUDIO_VAD_TRIGGER_FACTOR = 1.85
    AUDIO_VAD_MIN_RMS = 0.004
    AUDIO_MAX_GAIN = 3.60
    AUDIO_FILTER_ENABLED = False
    AUDIO_HIGHPASS_HZ = 110.0
    AUDIO_NOISE_GATE_FACTOR = 2.0
    AUDIO_NOISE_GATE_BLEND = 0.12
    AUDIO_NOISE_PROFILE_SUBTRACT_ENABLED = True
    AUDIO_NOISE_SUBTRACT_FACTOR = 0.30
    AUDIO_NOISE_FLOOR_KEEP = 0.12

MQTT_ENABLED = True
MQTT_BROKER_HOST = "localhost"
MQTT_BROKER_PORT = 1883
MQTT_USERNAME = None
MQTT_PASSWORD = None
MQTT_CLIENT_ID = "blanky-controller"
MQTT_TOPIC_PREFIX = "blanky"
MQTT_PULSE_SECONDS = 3.0

OPCUA_ENABLED = True
OPCUA_URL = "opc.tcp://192.168.30.3:4840"
OPCUA_NAMESPACE_INDEX = 4
OPCUA_PULSE_SECONDS = 0.3

# A wake word esta desativada no prototipo; fica documentada para trabalho futuro.
WAKEWORD_ENABLED = False
WAKEWORD_THRESHOLD = 0.55
WAKEWORD_COOLDOWN_SECONDS = 2.5
WAKEWORD_SAMPLE_RATE = 16000
WAKEWORD_FRAME_MS = 80
WAKEWORD_MODEL_NAME = "hey jarvis"
WAKEWORD_MODEL_PATH = None

TTS_VOICES_PT = ["alloy", "nova", "shimmer", "sage", "coral", "fable"]
TTS_VOICES_EN = ["alloy", "nova", "ash", "echo", "onyx", "fable"]
TTS_VOICE_DEFAULT_PT = "nova"
TTS_VOICE_DEFAULT_EN = "alloy"
STT_MODEL = "gpt-transcribe"
TTS_MODEL = "gpt-4o-mini-tts"

AUDIO_DIR = "audio"
INPUT_WAV = os.path.join(AUDIO_DIR, "input.wav")
TTS_WAV = os.path.join(AUDIO_DIR, "tts.wav")
BEEP_WAV = os.path.join(AUDIO_DIR, "beep.wav")

def ensure_dirs():
    os.makedirs(AUDIO_DIR, exist_ok=True)
