import QtQuick

QtObject {
    id: theme

    property string mode: "dark"
    readonly property bool dark: mode !== "light"
    readonly property bool colorIndependent: mode === "colorblind" || mode === "monochrome"
    readonly property bool highContrast: mode === "high_contrast"

    readonly property color background: mode === "light" ? "#d7e3ea"
        : mode === "high_contrast" ? "#000000"
        : mode === "colorblind" ? "#07121d"
        : mode === "monochrome" ? "#101010" : "#02060d"
    readonly property color backgroundTop: mode === "light" ? "#e3edf2"
        : mode === "high_contrast" ? "#080808"
        : mode === "colorblind" ? "#0b1c2b"
        : mode === "monochrome" ? "#1b1b1b" : "#03101b"
    readonly property color surface: mode === "light" ? "#c5d8e4"
        : mode === "high_contrast" ? "#111111"
        : mode === "colorblind" ? "#0d2030"
        : mode === "monochrome" ? "#181818" : "#091722"
    readonly property color surfaceSecondary: mode === "light" ? "#e3edf2"
        : mode === "high_contrast" ? "#050505"
        : mode === "colorblind" ? "#091825"
        : mode === "monochrome" ? "#252525" : "#07111a"
    readonly property color textPrimary: mode === "light" ? "#16384c" : "#f2f7fb"
    readonly property color textSecondary: mode === "light" ? "#386b85"
        : mode === "high_contrast" ? "#d2d2d2"
        : mode === "monochrome" ? "#c5c5c5" : "#a8d8ee"
    readonly property color textDisabled: mode === "light" ? "#526e7d" : "#8fa8b8"
    readonly property color border: mode === "light" ? "#5f98b8"
        : mode === "high_contrast" ? "#f2f2f2"
        : mode === "monochrome" ? "#c8c8c8" : "#1f6fa8"
    readonly property color borderStrong: mode === "light" ? "#0d5d8b"
        : mode === "high_contrast" ? "#ffffff"
        : mode === "monochrome" ? "#ffffff" : "#4ab7e8"
    readonly property color accent: mode === "light" ? "#0d5d8b"
        : mode === "high_contrast" ? "#00e5ff"
        : mode === "colorblind" ? "#4fc3f7"
        : mode === "monochrome" ? "#ffffff" : "#63cbff"
    readonly property color success: mode === "light" ? "#147a3d"
        : mode === "high_contrast" ? "#00e5ff"
        : mode === "colorblind" ? "#4fc3f7"
        : mode === "monochrome" ? "#f2f2f2" : "#48d66b"
    readonly property color warning: mode === "light" ? "#8a5b00"
        : mode === "high_contrast" ? "#ffd740"
        : mode === "colorblind" ? "#ffd166"
        : mode === "monochrome" ? "#d8d8d8" : "#f8c25d"
    readonly property color error: mode === "light" ? "#b32635"
        : mode === "high_contrast" ? "#ff8a65"
        : mode === "colorblind" ? "#ff9f43"
        : mode === "monochrome" ? "#ffffff" : "#ff6b6b"
    readonly property color inactive: mode === "light" ? "#526e7d"
        : mode === "high_contrast" ? "#c0c0c0"
        : mode === "monochrome" ? "#a8a8a8" : "#8fa8b8"
    readonly property color selected: mode === "light" ? "#146f9e"
        : mode === "high_contrast" ? "#00e5ff"
        : mode === "colorblind" ? "#4fc3f7"
        : mode === "monochrome" ? "#ffffff" : "#9dd9ff"
}
